version: '3'
services:

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - app

  app:
    build: .
    tty: true
    env_file:
      - .env
    command:
      bash -c "python src/manage.py migrate && python src/manage.py collectstatic && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    working_dir: /app
    networks:
      - app

networks:
  app:
