version: '3'
services:
  webapp:
    image: ghcr.io/protksen/impression_keeper:v0.1.5
    tty: true
    restart: always
    env_file:
      - .env
    working_dir: /app
    command:
      bash -c "python src/manage.py migrate && python src/manage.py collectstatic && python src/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    networks:
      - app

  db:
    container_name: postgres
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - app

networks:
  app:
