name: Create Pull Request

on:
  push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run:
          poetry install

      - name: Linters
        uses: pre-commit/action@v3.0.0

      - name: Test with pytest
        run:
          poetry run pytest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        run: |
          gh pr create -B main -H feature --title 'Merge feature into main' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
